[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_url = "${RPC_URL}" # Make sure you have set your RPC_URL in your environment variables

optimizer = true
optimizer_runs = 200
evm_version = "istanbul"